version: '3.1'
services: 
    db:
        image: mysql
        container_name: youbook
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
        - "3306:3306"
        volumes:
        - youbook_data:/var/lib/mysql
        
volumes: 
    youbook_data: