spring:
    datasource:
        url: jdbc:mysql://localhost:3306/books?createDatabaseIfNotExist=true&jdbcCompliantTruncation=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop